name: @name@
version: @version@
description: Bukkit plugin that lets you protect horses with signed saddles.
author: piratjsk
website: https://github.com/piratjsk/Sddls

main: @group@.Sddls
api-version: 1.13

commands:
  sddls:
    description: Prints information about plugin. With 'reload' argument reloads plugin configuration.

permissions:
  sddls.reload:
    description: Allows you to use 'sddls reload' command.
    default: op
  sddls.bypass:
    description: Allows you to bypass signed saddles protection.
    default: op
